USE `arenafifadb`;



DELIMITER $$
DROP PROCEDURE IF EXISTS `spGetSummaryHallOfFame` $$
CREATE PROCEDURE `spGetSummaryHallOfFame`()
begin      
	DECLARE _psnIDSerieAH2H VARCHAR(50) DEFAULT "";
	DECLARE _teamNameSerieAH2H VARCHAR(50) DEFAULT "";
	DECLARE _psnIDSerieAFUT VARCHAR(50) DEFAULT "";
	DECLARE _teamNameSerieAFUT VARCHAR(50) DEFAULT "";
	DECLARE _psnIDSerieAPRO VARCHAR(50) DEFAULT "";
	DECLARE _teamNameSerieAPRO VARCHAR(50) DEFAULT "";
	DECLARE _psnIDCDM VARCHAR(50) DEFAULT "";
	DECLARE _teamNameCDM VARCHAR(50) DEFAULT "";
	DECLARE _psnIDUCL VARCHAR(50) DEFAULT "";
	DECLARE _teamNameUCL VARCHAR(50) DEFAULT "";
	DECLARE _psnIDSCP VARCHAR(50) DEFAULT "";
	DECLARE _teamNameSCP VARCHAR(50) DEFAULT "";
	DECLARE _championshipID INTEGER DEFAULT 0;
	DECLARE _seasonIDCurrent INTEGER DEFAULT 0;
	DECLARE _seasonID INTEGER DEFAULT 0;
	
	SET _seasonIDCurrent = fcGetIdTempCurrent();

	SELECT ID_CAMPEONATO, ID_TEMPORADA into _championshipID, _seasonID
	FROM TB_CAMPEONATO
	WHERE ID_TEMPORADA < _seasonIDCurrent AND SG_TIPO_CAMPEONATO = "DIV1" 
	ORDER BY ID_CAMPEONATO DESC LIMIT 1;
	
	SELECT U.PSN_ID, T.NM_TIME into _psnIDSerieAH2H, _teamNameSerieAH2H
	FROM TB_HISTORICO_CONQUISTA H, TB_USUARIO U, TB_TIME T
	WHERE ID_TEMPORADA = _seasonID AND ID_CAMPEONATO = _championshipID
	AND H.ID_USUARIO_CAMPEAO = U.ID_USUARIO AND H.ID_TIME_CAMPEAO = T.ID_TIME;
	

	SELECT ID_CAMPEONATO, ID_TEMPORADA into _championshipID, _seasonID
	FROM TB_CAMPEONATO
	WHERE ID_TEMPORADA < _seasonIDCurrent AND SG_TIPO_CAMPEONATO = "FUT1" 
	ORDER BY ID_CAMPEONATO DESC LIMIT 1;
	
	SELECT U.PSN_ID, T.NM_TIME into _psnIDSerieAFUT, _teamNameSerieAFUT
	FROM TB_HISTORICO_CONQUISTA_FUT H, TB_USUARIO U, TB_TIME T
	WHERE ID_TEMPORADA = _seasonID AND ID_CAMPEONATO = _championshipID
	AND H.ID_USUARIO_CAMPEAO = U.ID_USUARIO AND H.ID_TIME_CAMPEAO = T.ID_TIME;
	

	SELECT ID_CAMPEONATO, ID_TEMPORADA into _championshipID, _seasonID
	FROM TB_CAMPEONATO
	WHERE ID_TEMPORADA < _seasonIDCurrent AND SG_TIPO_CAMPEONATO = "PRO1" 
	ORDER BY ID_CAMPEONATO DESC LIMIT 1;
	
	SELECT U.PSN_ID, T.NM_TIME into _psnIDSerieAPRO, _teamNameSerieAPRO
	FROM TB_HISTORICO_CONQUISTA_PRO H, TB_USUARIO U, TB_TIME T
	WHERE ID_TEMPORADA = _seasonID AND ID_CAMPEONATO = _championshipID
	AND H.ID_USUARIO_CAMPEAO = U.ID_USUARIO AND H.ID_TIME_CAMPEAO = T.ID_TIME;
	
	
	
	SELECT ID_CAMPEONATO, ID_TEMPORADA into _championshipID, _seasonID
	FROM TB_CAMPEONATO
	WHERE ID_TEMPORADA < _seasonIDCurrent AND SG_TIPO_CAMPEONATO = "PRO1" 
	ORDER BY ID_CAMPEONATO DESC LIMIT 1;
	
	SELECT U.PSN_ID, T.NM_TIME into _psnIDSerieAPRO, _teamNameSerieAPRO
	FROM TB_HISTORICO_CONQUISTA_PRO H, TB_USUARIO U, TB_TIME T
	WHERE ID_TEMPORADA = _seasonID AND ID_CAMPEONATO = _championshipID
	AND H.ID_USUARIO_CAMPEAO = U.ID_USUARIO AND H.ID_TIME_CAMPEAO = T.ID_TIME;
	

	SELECT ID_CAMPEONATO, ID_TEMPORADA into _championshipID, _seasonID
	FROM TB_CAMPEONATO
	WHERE ID_TEMPORADA < _seasonIDCurrent AND SG_TIPO_CAMPEONATO = "CPDM" 
	ORDER BY ID_CAMPEONATO DESC LIMIT 1;
	
	SELECT U.PSN_ID, T.NM_TIME into _psnIDCDM, _teamNameCDM
	FROM TB_HISTORICO_CONQUISTA H, TB_USUARIO U, TB_TIME T
	WHERE ID_TEMPORADA = _seasonID AND ID_CAMPEONATO = _championshipID
	AND H.ID_USUARIO_CAMPEAO = U.ID_USUARIO AND H.ID_TIME_CAMPEAO = T.ID_TIME;
	

	SELECT ID_CAMPEONATO, ID_TEMPORADA into _championshipID, _seasonID
	FROM TB_CAMPEONATO
	WHERE ID_TEMPORADA < _seasonIDCurrent AND SG_TIPO_CAMPEONATO = "CPGL" AND IN_CAMPEONATO_GRUPO = true
	ORDER BY ID_CAMPEONATO DESC LIMIT 1;
	
	SELECT U.PSN_ID, T.NM_TIME into _psnIDUCL, _teamNameUCL
	FROM TB_HISTORICO_CONQUISTA H, TB_USUARIO U, TB_TIME T
	WHERE ID_TEMPORADA = _seasonID AND ID_CAMPEONATO = _championshipID
	AND H.ID_USUARIO_CAMPEAO = U.ID_USUARIO AND H.ID_TIME_CAMPEAO = T.ID_TIME;
	

	SELECT ID_CAMPEONATO, ID_TEMPORADA into _championshipID, _seasonID
	FROM TB_CAMPEONATO
	WHERE ID_TEMPORADA < _seasonIDCurrent AND SG_TIPO_CAMPEONATO = "MDCL" AND IN_CAMPEONATO_GRUPO = false
	ORDER BY ID_CAMPEONATO DESC LIMIT 1;
	
	SELECT U.PSN_ID, T.NM_TIME into _psnIDSCP, _teamNameSCP
	FROM TB_HISTORICO_CONQUISTA H, TB_USUARIO U, TB_TIME T
	WHERE ID_TEMPORADA = _seasonID AND ID_CAMPEONATO = _championshipID
	AND H.ID_USUARIO_CAMPEAO = U.ID_USUARIO AND H.ID_TIME_CAMPEAO = T.ID_TIME;
	


	SELECT _psnIDSerieAH2H as psnIDH2HChampion, _teamNameSerieAH2H as teamNameH2HChampion,
		   _psnIDSerieAFUT as psnIDFUTChampion, _teamNameSerieAFUT as teamNameFUTChampion,
		   _psnIDSerieAPRO as psnIDPROChampion, _teamNameSerieAPRO as teamNamePROChampion,
		   _psnIDCDM as psnIDCDMChampion, _teamNameCDM as teamNameCDMChampion,
		   _psnIDUCL as psnIDUCLChampion, _teamNameUCL as teamNameUCLChampion,
		   _psnIDSCP as psnIDSCPChampion, _teamNameSCP as teamNameSCPChampion;
   
End$$
DELIMITER ;



DELIMITER $$
DROP PROCEDURE IF EXISTS `spGetSummaryRanking` $$
CREATE PROCEDURE `spGetSummaryRanking`()
begin      
	DECLARE _goalsH2H INTEGER DEFAULT 0;
	DECLARE _goalsFUT INTEGER DEFAULT 0;
	DECLARE _goalsPRO INTEGER DEFAULT 0;
	DECLARE _seasonNameH2H VARCHAR(50) DEFAULT "";
	DECLARE _seasonNameFUT VARCHAR(50) DEFAULT "";
	DECLARE _seasonNamePRO VARCHAR(50) DEFAULT "";
	DECLARE _seasonID INTEGER DEFAULT 0;
	
	SET _seasonID = fcGetIdTempCurrent();

	SELECT NM_TEMPORADA into _seasonNameH2H
	FROM TB_TEMPORADA
	WHERE ID_TEMPORADA = _seasonID;
	
	SELECT SUM(T.QT_GOLS_TIME_CASA+T.QT_GOLS_TIME_VISITANTE) into _goalsH2H
	FROM TB_TABELA_JOGO T
	WHERE ID_CAMPEONATO IN (SELECT ID_CAMPEONATO FROM TB_CAMPEONATO WHERE ID_TEMPORADA = _seasonID AND FIND_IN_SET(SG_TIPO_CAMPEONATO,fcGetAllSiglaByMode('H2H')))
	AND T.QT_GOLS_TIME_CASA IS NOT NULL;
	
	SELECT SUM(T.QT_GOLS_TIME_CASA+T.QT_GOLS_TIME_VISITANTE) into _goalsFUT
	FROM TB_TABELA_JOGO T
	WHERE ID_CAMPEONATO IN (SELECT ID_CAMPEONATO FROM TB_CAMPEONATO WHERE ID_TEMPORADA = _seasonID AND FIND_IN_SET(SG_TIPO_CAMPEONATO,fcGetAllSiglaByMode('FUT')))
	AND T.QT_GOLS_TIME_CASA IS NOT NULL;
	
	SELECT SUM(T.QT_GOLS_TIME_CASA+T.QT_GOLS_TIME_VISITANTE) into _goalsPRO
	FROM TB_TABELA_JOGO T
	WHERE ID_CAMPEONATO IN (SELECT ID_CAMPEONATO FROM TB_CAMPEONATO WHERE ID_TEMPORADA = _seasonID AND FIND_IN_SET(SG_TIPO_CAMPEONATO,fcGetAllSiglaByMode('PRO')))
	AND T.QT_GOLS_TIME_CASA IS NOT NULL;
	
	SELECT _goalsH2H as totalGoalsH2H, _goalsFUT as totalGoalsFUT,
		   _goalsPRO as totalGoalsPRO, _seasonNameH2H as seasonNameH2H,
		   _seasonNameH2H as seasonNameFUT, _seasonNameH2H as seasonNamePRO;
   
End$$
DELIMITER ;



DELIMITER $$
DROP PROCEDURE IF EXISTS `spGetSummaryRankingListScorers` $$
CREATE PROCEDURE `spGetSummaryRankingListScorers`(pMode VARCHAR(3))
begin      
	DECLARE _seasonID INTEGER DEFAULT 0;
	
	SET _seasonID = fcGetIdTempCurrent();
	
	SELECT X.ID_GOLEADOR, G.NM_GOLEADOR, X.QT_GOLS_MARCADOS, T.NM_TIME, T.DS_Tipo, G.NM_GOLEADOR_COMPLETO, fcGetCurrentPsnIDByTime(0,T.ID_TIME) as PSN_ID
	FROM (SELECT J.ID_GOLEADOR, SUM(J.QT_GOLS) as QT_GOLS_MARCADOS
	FROM TB_GOLEADOR_JOGO J
	WHERE J.ID_CAMPEONATO IN (SELECT C.ID_CAMPEONATO FROM TB_CAMPEONATO C WHERE FIND_IN_SET(SG_TIPO_CAMPEONATO,fcGetAllSiglaByMode(pMode)))
	GROUP BY J.ID_GOLEADOR) X, TB_GOLEADOR G, TB_TIME T
	WHERE G.ID_TIME IN (SELECT CT.ID_TIME FROM TB_CAMPEONATO_TIME CT, TB_CAMPEONATO C WHERE FIND_IN_SET(SG_TIPO_CAMPEONATO,fcGetAllSiglaByMode(pMode)) AND CT.ID_CAMPEONATO = C.ID_CAMPEONATO GROUP BY CT.ID_TIME)
	AND X.ID_GOLEADOR = G.ID_GOLEADOR
	AND G.ID_TIME = T.ID_TIME
	ORDER BY X.QT_GOLS_MARCADOS DESC, G.NM_GOLEADOR LIMIT 5;	

End$$
DELIMITER ;
