USE `arenafifadb`;

DELIMITER $$
DROP PROCEDURE IF EXISTS `spAddCampeonatoUsuario` $$
CREATE PROCEDURE `spAddCampeonatoUsuario`(    
    pIdCamp INTEGER,     
    pIdUsu INTEGER
)
Begin
	insert into `TB_CAMPEONATO_USUARIO` (`ID_CAMPEONATO`, `ID_USUARIO`, `DT_ENTRADA`) 
	values (pIdCamp, pIdUsu, now());
End$$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS `spDeleteCampeonatoUsuario` $$
CREATE PROCEDURE `spDeleteCampeonatoUsuario`(    
    pIdCamp INTEGER,     
    pIdUsu INTEGER
)
Begin
	DELETE FROM TB_CAMPEONATO_USUARIO 
	WHERE ID_CAMPEONATO = pIdCamp AND ID_USUARIO = pIdUsu;
End$$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS `spUpdateCampeonatoUsuarioNewUsuario` $$
CREATE PROCEDURE `spUpdateCampeonatoUsuarioNewUsuario`(    
    pIdCamp INTEGER,     
    pIdUsuOld INTEGER,
    pIdUsuNew INTEGER,
	pPsnUsuOperacao VARCHAR(30),
	pIdUsuarioOperacao INTEGER,
	pDsPaginaOperacao VARCHAR(30)
)
Begin
	DECLARE _nmCamp VARCHAR(50) DEFAULT NULL;

	select NM_CAMPEONATO into _nmCamp 
	from TB_CAMPEONATO
	where ID_CAMPEONATO = pIdCamp;

    update `TB_CAMPEONATO_USUARIO` 
	set ID_USUARIO = pIdUsuNew, DT_ENTRADA = now()
	where ID_CAMPEONATO = pIdCamp and ID_USUARIO = pIdUsuOld;

    call `arenafifadb`.`spAddHistAltCampeonato`(pIdCamp, pIdUsuarioOperacao, 'TROCANDO TECNICO DO CAMPEONATO', pPsnUsuOperacao, _nmCamp, pDsPaginaOperacao);
End$$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS `spTransferCampeonatoUsuarioNewCampeonato` $$
CREATE PROCEDURE `spTransferCampeonatoUsuarioNewCampeonato`(    
    pIdCampOld INTEGER,     
    pIdCampNew INTEGER
)
Begin
	insert into `TB_CAMPEONATO_USUARIO` (`ID_CAMPEONATO`, `ID_USUARIO`, `DT_ENTRADA`)
	select pIdCampNew, `ID_USUARIO`, `DT_ENTRADA`
    from `TB_CAMPEONATO_USUARIO` 
	where ID_CAMPEONATO = pIdCampOld;
End$$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS `spGetAllUsuariosOfCampeonato` $$
CREATE PROCEDURE `spGetAllUsuariosOfCampeonato`(pIdCamp INTEGER)
begin      
   select U.ID_USUARIO, U.NM_USUARIO, U.PSN_ID, U.DS_EMAIL 
   from TB_USUARIO U, TB_CAMPEONATO_USUARIO C 
   where C.ID_CAMPEONATO = pIdCamp
   and fcGetIdUsuariosVazio(C.ID_USUARIO,'NOT')
   and C.ID_USUARIO = U.ID_USUARIO
   order by U.NM_USUARIO;      
End$$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS `spGetAllUsuariosOfCampeonatoByTipo` $$
CREATE PROCEDURE `spGetAllUsuariosOfCampeonatoByTipo`(pTipo VARCHAR(10))
begin      
   select U.ID_USUARIO, U.NM_USUARIO, U.PSN_ID, U.DS_EMAIL
   from TB_USUARIO U, TB_CAMPEONATO_USUARIO C 
   where C.ID_CAMPEONATO = fcGetIdCurrentCampeonatoByTipo(pTipo)
   and fcGetIdUsuariosVazio(C.ID_USUARIO,'NOT')
   and C.ID_USUARIO = U.ID_USUARIO
   order by U.NM_USUARIO;      
End$$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS `spDeleteAllCampeonatoUsuarioOfCampeonato` $$
CREATE PROCEDURE `spDeleteAllCampeonatoUsuarioOfCampeonato`(pIdCamp INTEGER)
Begin
    delete from `TB_CAMPEONATO_USUARIO` 
	where ID_CAMPEONATO = pIdCamp;
End$$
DELIMITER ;




DELIMITER $$
DROP PROCEDURE IF EXISTS `spAddLoadCampeonatoUsuarioOfCampeonato` $$
CREATE PROCEDURE `spAddLoadCampeonatoUsuarioOfCampeonato`(    
    pIdCamp INTEGER,     
    pIdsUsu VARCHAR(250)
)
Begin
	DECLARE _next VARCHAR(250) DEFAULT NULL;
	DECLARE _nextlen INTEGER DEFAULT NULL;
	DECLARE _idUsu VARCHAR(5) DEFAULT NULL;
	DECLARE strDelimiter CHAR(1) DEFAULT ',';
	
	call `arenafifadb`.`spDeleteAllCampeonatoUsuarioOfCampeonato`(pIdCamp);

	iterator:
	LOOP
		IF LENGTH(TRIM(pIdsUsu)) = 0 OR pIdsUsu IS NULL THEN
			LEAVE iterator;
		END IF;
		
		SET _next = SUBSTRING_INDEX(pIdsUsu,',',1);
		
		SET _nextlen = LENGTH(_next);
		
		SET _idUsu = TRIM(_next);
		
		insert into `TB_CAMPEONATO_USUARIO` (`ID_CAMPEONATO`, `ID_USUARIO`) 
		values (pIdCamp, CAST(_idUsu AS SIGNED));
		
		SET pIdsUsu = INSERT(pIdsUsu,1,_nextlen + 1,'');
	END LOOP;
End$$
DELIMITER ;



DELIMITER $$
DROP PROCEDURE IF EXISTS `spGetAllCampeonatoUsuarioToExchange` $$
CREATE PROCEDURE `spGetAllCampeonatoUsuarioToExchange`(pIdCamp INTEGER, pTipo VARCHAR(4))
Begin
	
	IF pTipo = 'DIV1' OR pTipo = 'DIV2' OR pTipo = 'DIV3' THEN
	
		SELECT U.ID_USUARIO, U.NM_USUARIO, U.PSN_ID, U.DS_ESTADO, U.DS_EMAIL
		FROM TB_USUARIO U
		WHERE U.ID_USUARIO NOT IN (SELECT X.ID_USUARIO FROM TB_CAMPEONATO_USUARIO X WHERE X.ID_CAMPEONATO = pIdCamp)
		AND U.IN_DESEJA_PARTICIPAR = 1
		AND NOT EXISTS (SELECT XX.ID_USUARIO FROM TB_CAMPEONATO_USUARIO XX, TB_CAMPEONATO CC WHERE fcGetIdUsuariosVazio(XX.ID_USUARIO,'IN')
						AND CC.ID_TEMPORADA = _idTemp AND CC.SG_TIPO_CAMPEONATO IN ('DIV1','DIV2','DIV3','DIV4')
						AND XX.ID_CAMPEONATO = CC.ID_CAMPEONATO AND XX.ID_USUARIO = U.ID_USUARIO)
		ORDER BY U.NM_Usuario;
	
	ELSEIF pTipo = 'DIV4' THEN
	
		SELECT U.ID_USUARIO, U.NM_USUARIO, U.PSN_ID, U.DS_ESTADO, U.DS_EMAIL, ID_BANCO_RESERVA FROM TB_LISTA_BANCO_RESERVA B, TB_USUARIO U 
		WHERE B.ID_USUARIO = U.ID_USUARIO AND B.TP_BANCO_RESERVA = 'H2H' AND B.IN_CONSOLE = 'PS4' AND B.DT_FIM IS NULL
		UNION ALL 
		SELECT U.ID_USUARIO, U.NM_USUARIO, U.PSN_ID, U.DS_ESTADO, U.DS_EMAIL, 10000 as ID_BANCO_RESERVA
		FROM TB_USUARIO U
		WHERE fcGetIdUsuariosVazio(U.ID_USUARIO,'IN')
		AND NOT EXISTS (SELECT XX.ID_USUARIO FROM TB_CAMPEONATO_USUARIO XX, TB_CAMPEONATO CC WHERE fcGetIdUsuariosVazio(XX.ID_USUARIO,'IN')
						AND CC.ID_TEMPORADA = _idTemp AND CC.SG_TIPO_CAMPEONATO IN ('DIV1','DIV2','DIV3','DIV4')
						AND XX.ID_CAMPEONATO = CC.ID_CAMPEONATO AND XX.ID_USUARIO = U.ID_USUARIO)
		AND U.ID_USUARIO NOT IN (SELECT H.ID_USUARIO FROM TB_CAMPEONATO_USUARIO H WHERE H.ID_CAMPEONATO = pIdCamp)
		ORDER BY ID_BANCO_RESERVA, ID_USUARIO;
	
	ELSEIF pTipo = 'FUT1' THEN
	
		SELECT U.ID_USUARIO, U.NM_USUARIO, U.PSN_ID, U.DS_ESTADO, U.DS_EMAIL, ID_BANCO_RESERVA FROM TB_LISTA_BANCO_RESERVA B, TB_USUARIO U 
		WHERE B.ID_USUARIO = U.ID_USUARIO AND B.TP_BANCO_RESERVA = 'FUT' AND B.IN_CONSOLE = 'PS4' AND B.DT_FIM IS NULL
		UNION ALL 
		SELECT U.ID_USUARIO, U.NM_USUARIO, U.PSN_ID, U.DS_ESTADO, U.DS_EMAIL, 10000 as ID_BANCO_RESERVA
		FROM TB_USUARIO U
		WHERE fcGetIdUsuariosVazio(U.ID_USUARIO,'IN')
		AND NOT EXISTS (SELECT XX.ID_USUARIO FROM TB_CAMPEONATO_USUARIO XX, TB_CAMPEONATO CC WHERE fcGetIdUsuariosVazio(XX.ID_USUARIO,'IN')
						AND CC.ID_TEMPORADA = _idTemp AND CC.SG_TIPO_CAMPEONATO IN ('FUT1','FUT2')
						AND XX.ID_CAMPEONATO = CC.ID_CAMPEONATO AND XX.ID_USUARIO = U.ID_USUARIO)
		AND U.ID_USUARIO NOT IN (SELECT H.ID_USUARIO FROM TB_CAMPEONATO_USUARIO H WHERE H.ID_CAMPEONATO = pIdCamp)
		ORDER BY ID_BANCO_RESERVA, ID_USUARIO;
	
	ELSEIF pTipo = 'PRO1' THEN
	
		SELECT U.ID_USUARIO, U.NM_USUARIO, U.PSN_ID, U.DS_ESTADO, U.DS_EMAIL, ID_BANCO_RESERVA FROM TB_LISTA_BANCO_RESERVA B, TB_USUARIO U 
		WHERE B.ID_USUARIO = U.ID_USUARIO AND B.TP_BANCO_RESERVA = 'PRO' AND B.IN_CONSOLE = 'PS4' AND B.DT_FIM IS NULL
		UNION ALL 
		SELECT U.ID_USUARIO, U.NM_USUARIO, U.PSN_ID, U.DS_ESTADO, U.DS_EMAIL, 10000 as ID_BANCO_RESERVA
		FROM TB_USUARIO U
		WHERE fcGetIdUsuariosVazio(U.ID_USUARIO,'IN')
		AND NOT EXISTS (SELECT XX.ID_USUARIO FROM TB_CAMPEONATO_USUARIO XX, TB_CAMPEONATO CC WHERE fcGetIdUsuariosVazio(XX.ID_USUARIO,'IN')
						AND CC.ID_TEMPORADA = _idTemp AND CC.SG_TIPO_CAMPEONATO IN ('PRO1','PRO2')
						AND XX.ID_CAMPEONATO = CC.ID_CAMPEONATO AND XX.ID_USUARIO = U.ID_USUARIO)
		AND U.ID_USUARIO NOT IN (SELECT H.ID_USUARIO FROM TB_CAMPEONATO_USUARIO H WHERE H.ID_CAMPEONATO = pIdCamp)
		ORDER BY ID_BANCO_RESERVA, ID_USUARIO;
	
	END IF;
End$$
DELIMITER ;

