USE `arenafifadb`;



ALTER TABLE TB_COMENTARIO_JOGO MODIFY DT_COMENTARIO DATE;

DELIMITER $$
DROP PROCEDURE IF EXISTS `spAddComentarioJogo` $$
CREATE PROCEDURE `spAddComentarioJogo`(    
    pIdJogo INTEGER,     
    pIdUsu INTEGER,
	pDsComentario LONGTEXT
)
Begin
	DECLARE _total INTEGER DEFAULT 0;
	
	select count(1) into _total
	from TB_COMENTARIO_JOGO
	where ID_TABELA_JOGO = pIdJogo
	and ID_USUARIO = pIdUsu
	and DS_COMENTARIO = pDsComentario
	and DT_COMENTARIO = CURDATE();
	
	IF _total = 0 THEN

		insert into `TB_COMENTARIO_JOGO` (`ID_TABELA_JOGO`, `ID_USUARIO`, `DT_COMENTARIO`, `HR_COMENTARIO`, `DS_COMENTARIO`) 
		values (pIdJogo, pIdUsu, CURDATE(), DATE_FORMAT(CURRENT_TIME(), '%H:%i'), pDsComentario);
	
	END IF;
End$$
DELIMITER ;

DELIMITER $$
DROP PROCEDURE IF EXISTS `spAddAllComentarioJogoByTime` $$
CREATE PROCEDURE `spAddAllComentarioJogoByTime`(    
    pIdCamp INTEGER,     
    pIdTime INTEGER,
    pIdUsu INTEGER,     
	pDsComentario LONGTEXT
)
Begin
	INSERT INTO TB_COMENTARIO_JOGO (ID_TABELA_JOGO, ID_USUARIO, DT_COMENTARIO, HR_COMENTARIO, DS_COMENTARIO)
		SELECT ID_TABELA_JOGO, pIdUsu, CURDATE(), DATE_FORMAT(CURRENT_TIME(), '%H:%i'), pDsComentario 
		FROM TB_TABELA_JOGO WHERE ID_Campeonato = pIdCamp AND DT_EFETIVACAO_JOGO IS NULL AND DT_TABELA_INICIO_JOGO <= CURDATE()
		AND (ID_TIME_CASA = pIdTime OR ID_TIME_VISITANTE = pIdTime)
		ORDER BY ID_Tabela_Jogo;
End$$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS `spGetAllComentarioJogoByJogo` $$
CREATE PROCEDURE `spGetAllComentarioJogoByJogo`(pIdJogo INTEGER)
begin      
	DECLARE _idCamp INTEGER DEFAULT NULL;
	DECLARE _sgCamp VARCHAR(4) DEFAULT NULL;
	DECLARE _idTime INTEGER DEFAULT NULL;
	DECLARE _typeCamp VARCHAR(3) DEFAULT NULL;
	
	SELECT ID_CAMPEONATO, SG_TIPO_CAMPEONATO into _idCamp, _sgCamp
	FROM TB_CAMPEONATO WHERE ID_CAMPEONATO IN (SELECT ID_CAMPEONATO FROM TB_TABELA_JOGO WHERE ID_TABELA_JOGO = pIdJogo);
	
	IF _sgCamp = "CPDM" OR _sgCamp = "ERCP" THEN
	
	   select CJ.*, TU.NM_Usuario, TU.PSN_ID, TU.IN_USUARIO_MODERADOR, (SELECT NM_TIME FROM TB_TIME WHERE ID_TIME = fcGetCurrentIdTimeCDM(CJ.ID_USUARIO)) as NM_TIME
	   from TB_COMENTARIO_JOGO CJ, TB_USUARIO TU
	   where CJ.ID_TABELA_JOGO = pIdJogo
	   and CJ.ID_USUARIO = TU.ID_USUARIO
	   order by CJ.ID_COMENTARIO;

	ELSE
	
		SET _typeCamp = fcGetTypeModelOfCampeonato(_sgCamp);
		
		IF _typeCamp = "H2H" THEN
		
		   select CJ.*, TU.NM_Usuario, TU.PSN_ID, TU.IN_USUARIO_MODERADOR, (SELECT NM_TIME FROM TB_TIME WHERE ID_TIME = fcGetCurrentIdTimeH2H(CJ.ID_USUARIO)) as NM_TIME
		   from TB_COMENTARIO_JOGO CJ, TB_USUARIO TU
		   where CJ.ID_TABELA_JOGO = pIdJogo
		   and CJ.ID_USUARIO = TU.ID_USUARIO
		   order by CJ.ID_COMENTARIO;

		ELSEIF _typeCamp = "FUT" THEN
		
		   select CJ.*, TU.NM_Usuario, TU.PSN_ID, TU.IN_USUARIO_MODERADOR, (SELECT NM_TIME FROM TB_TIME WHERE ID_TIME = fcGetCurrentIdTimeFUT(CJ.ID_USUARIO)) as NM_TIME
		   from TB_COMENTARIO_JOGO CJ, TB_USUARIO TU
		   where CJ.ID_TABELA_JOGO = pIdJogo
		   and CJ.ID_USUARIO = TU.ID_USUARIO
		   order by CJ.ID_COMENTARIO;

		ELSE
		
		   select CJ.*, TU.NM_Usuario, TU.PSN_ID, TU.IN_USUARIO_MODERADOR, (SELECT NM_TIME FROM TB_TIME WHERE ID_TIME = fcGetCurrentIdTimePRO(CJ.ID_USUARIO)) as NM_TIME
		   from TB_COMENTARIO_JOGO CJ, TB_USUARIO TU
		   where CJ.ID_TABELA_JOGO = pIdJogo
		   and CJ.ID_USUARIO = TU.ID_USUARIO
		   order by CJ.ID_COMENTARIO;
		
		END IF;
	
	END IF;
End$$
DELIMITER ;


