USE `arenafifadb`;


DELIMITER $$
DROP PROCEDURE IF EXISTS `spGetAchievementH2H` $$
CREATE PROCEDURE `spGetAchievementH2H`()
begin      
	SELECT C.SG_TIPO_CAMPEONATO, E.ID_TEMPORADA, E.NM_TEMPORADA, C.IN_CAMPEONATO_GRUPO, C.IN_CONSOLE, U.PSN_ID, U.NM_USUARIO, T.NM_TIME, T.DS_TIPO
	FROM TB_HISTORICO_CONQUISTA H, TB_CAMPEONATO C, TB_TEMPORADA E, TB_USUARIO U, TB_TIME T
	WHERE C.SG_TIPO_CAMPEONATO NOT IN ('FUT1', 'FUT2', 'CFUT', 'LFUT', 'PRO1', 'PRO2', 'CPRO')
	AND H.ID_TEMPORADA = C.ID_TEMPORADA
	AND H.ID_CAMPEONATO = C.ID_CAMPEONATO
	AND H.ID_TEMPORADA = E.ID_TEMPORADA
	AND C.ID_TEMPORADA = E.ID_TEMPORADA
	AND H.ID_USUARIO_CAMPEAO = U.ID_USUARIO
	AND H.ID_TIME_CAMPEAO = T.ID_TIME
	GROUP BY C.SG_TIPO_CAMPEONATO, E.NM_TEMPORADA, C.IN_CAMPEONATO_GRUPO, C.IN_CONSOLE, U.PSN_ID, U.NM_USUARIO, T.NM_TIME, T.DS_TIPO
    ORDER BY SG_TIPO_CAMPEONATO, ID_TEMPORADA DESC, IN_CAMPEONATO_GRUPO, IN_CONSOLE;
End$$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS `spGetAchievementFUT` $$
CREATE PROCEDURE `spGetAchievementFUT`()
begin      
	SELECT C.SG_TIPO_CAMPEONATO, E.ID_TEMPORADA, E.NM_TEMPORADA, C.IN_CAMPEONATO_GRUPO, C.IN_CONSOLE, U.PSN_ID, U.NM_USUARIO, T.NM_TIME, T.DS_TIPO
	FROM TB_HISTORICO_CONQUISTA_FUT H, TB_CAMPEONATO C, TB_TEMPORADA E, TB_USUARIO U, TB_TIME T
	WHERE C.SG_TIPO_CAMPEONATO IN ('FUT1', 'FUT2', 'CFUT', 'LFUT')
	AND H.ID_TEMPORADA = C.ID_TEMPORADA
	AND H.ID_CAMPEONATO = C.ID_CAMPEONATO
	AND H.ID_TEMPORADA = E.ID_TEMPORADA
	AND C.ID_TEMPORADA = E.ID_TEMPORADA
	AND H.ID_USUARIO_CAMPEAO = U.ID_USUARIO
	AND H.ID_TIME_CAMPEAO = T.ID_TIME
	GROUP BY C.SG_TIPO_CAMPEONATO, E.NM_TEMPORADA, C.IN_CAMPEONATO_GRUPO, C.IN_CONSOLE, U.PSN_ID, U.NM_USUARIO, T.NM_TIME, T.DS_TIPO
    ORDER BY SG_TIPO_CAMPEONATO, ID_TEMPORADA DESC, IN_CAMPEONATO_GRUPO, IN_CONSOLE;
End$$
DELIMITER ;

DELIMITER $$
DROP PROCEDURE IF EXISTS `spGetAchievementPRO` $$
CREATE PROCEDURE `spGetAchievementPRO`()
begin      
	SELECT C.SG_TIPO_CAMPEONATO, E.ID_TEMPORADA, E.NM_TEMPORADA, C.IN_CAMPEONATO_GRUPO, C.IN_CONSOLE, U.PSN_ID, U.NM_USUARIO, T.NM_TIME, T.DS_TIPO
	FROM TB_HISTORICO_CONQUISTA_PRO H, TB_CAMPEONATO C, TB_TEMPORADA E, TB_USUARIO U, TB_TIME T
	WHERE C.SG_TIPO_CAMPEONATO IN ('PRO1', 'PRO2', 'CPRO')
	AND H.ID_TEMPORADA = C.ID_TEMPORADA
	AND H.ID_CAMPEONATO = C.ID_CAMPEONATO
	AND H.ID_TEMPORADA = E.ID_TEMPORADA
	AND C.ID_TEMPORADA = E.ID_TEMPORADA
	AND H.ID_USUARIO_CAMPEAO = U.ID_USUARIO
	AND H.ID_TIME_CAMPEAO = T.ID_TIME
	GROUP BY C.SG_TIPO_CAMPEONATO, E.NM_TEMPORADA, C.IN_CAMPEONATO_GRUPO, C.IN_CONSOLE, U.PSN_ID, U.NM_USUARIO, T.NM_TIME, T.DS_TIPO
    ORDER BY SG_TIPO_CAMPEONATO, ID_TEMPORADA DESC, IN_CAMPEONATO_GRUPO, IN_CONSOLE;
End$$
DELIMITER ;