USE `arena_blog`;

ALTER TABLE TB_BLOG_MODERADOR MODIFY DT_BLOG DATE;


DELIMITER $$
DROP FUNCTION IF EXISTS `fcGetNewIdBlog` $$
CREATE FUNCTION `fcGetNewIdBlog`(pIdUser INTEGER) RETURNS INTEGER
	DETERMINISTIC
begin

	DECLARE _idBlog INTEGER DEFAULT NULL;
	
	SELECT H.id_blog into _idBlog FROM TB_BLOG_MODERADOR H 
	WHERE H.ID_MODERADOR =  pIdUser ORDER BY H.ID_BLOG DESC LIMIT 1;
	
	IF (_idBlog IS NULL) THEN
		SET _idBlog = 1;
	ELSE
		SET _idBlog = _idBlog + 1;
	END IF;
	
	RETURN _idBlog;
End$$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS `spAddBlog` $$
CREATE PROCEDURE `spAddBlog`(
	pIdUser INTEGER,
	pTitle VARCHAR(200),
	pDate DATE,
	pHour VARCHAR(8),
	pText LONGTEXT
)
begin
	insert into TB_BLOG_MODERADOR (ID_MODERADOR, ID_BLOG, DT_BLOG, HR_BLOG, DS_TITULO, DS_TEXTO_BLOG)
	values (pIdUser, fcGetNewIdBlog(pIdUser), pDate, pHour, pTitle, pText);
End$$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS `spUpdateBlog` $$
CREATE PROCEDURE `spUpdateBlog`(
	pIdUser INTEGER,
	pIdBlog INTEGER,
	pTitle VARCHAR(200),
	pText LONGTEXT
)
begin
	UPDATE TB_BLOG_MODERADOR 
	SET DS_TITULO = pTitle, DS_TEXTO_BLOG = pText
	WHERE ID_MODERADOR = pIdUser
	AND ID_BLOG = pIdBlog;
End$$
DELIMITER ;



DELIMITER $$
DROP PROCEDURE IF EXISTS `spGetAllBlogNoFilterCRUD` $$
CREATE PROCEDURE `spGetAllBlogNoFilterCRUD`()
begin      
   select B.*, U.NM_USUARIO, U.PSN_ID, DATE_FORMAT(DT_BLOG,'%d/%m/%Y') as DT_BLOG_FORMATADA
   from TB_BLOG_MODERADOR B, TB_USUARIO U
   where B.ID_MODERADOR = U.ID_USUARIO
   order by B.DT_BLOG DESC, B.HR_BLOG DESC;      
End$$
DELIMITER ;



DELIMITER $$
DROP PROCEDURE IF EXISTS `spGetBlog` $$
CREATE PROCEDURE `spGetBlog`(pIdUser INTEGER, pIdBlog INTEGER)
begin      
   select B.*, U.NM_USUARIO, U.PSN_ID, DATE_FORMAT(DT_BLOG,'%d/%m/%Y') as DT_BLOG_FORMATADA
   from TB_BLOG_MODERADOR B, TB_USUARIO U
	WHERE B.ID_MODERADOR = pIdUser
	AND B.ID_BLOG = pIdBlog
    AND B.ID_MODERADOR = U.ID_USUARIO;      
End$$
DELIMITER ;



DELIMITER $$
DROP PROCEDURE IF EXISTS `spDeleteBlog` $$
CREATE PROCEDURE `spDeleteBlog`(pIdUser INTEGER, pIdBlog INTEGER)
begin      
   DELETE FROM TB_BLOG_MODERADOR
	WHERE ID_MODERADOR = pIdUser
	AND ID_BLOG = pIdBlog;
End$$
DELIMITER ;


